ServerSpawn:
  x: 0
  y: 0
  z: 0
  world: Lobby

Snake:
  TimeToStart: 600
  TimeToRestart: 300
  ArenaHeight: 200
  ArenaRadius: 30
  ConstructionTime: 600
  World: "Patata"
  Lobby:
    x: 0
    y: 0
    z: 0
  Join:
    x: -68
    y: -59
    z: -7
  Leave:
    x: -68
    y: -59
    z: -10
  Arena:
    x: 0
    y: -63
    z: 0
Worlds:
  - Lobby
  - Patata
